# Force deploy
name: Depoly to tech.libresinn.com/cheetsheets
on:
  push:
    branches:
      - main

jobs:
  build:
    name: BUILD
    runs-on: ubuntu-latest
    
    steps:
    # Need to use Node to build static site
    - name: USE NODE.JS CURRENT
      uses: actions/setup-node@v3
      with:
        node-version: current
    
    - name: INSTALL DEPENDENCIES & BUILD
      run: |
        cd ..
        pwd
        ls -la
        npm i
        npm run build

    - uses: actions/checkout@v3
    - name: DEPLOY
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.CHEATSHEET_HOST }}
        username: ${{ secrets.CHEATSHEET_USERNAME }}
        password: ${{ secrets.CHEATSHEET_PASSWORD }}
        port: ${{ secrets.CHEATSHEET_PORT }}
        rm: true
        source: "_site"
        target: "/home/dh_swaz4r/tech.libresinn.com/cheatsheets"
