# Force deploy
name: Depoly to tech.libresinn.com/cheetsheets
on:
  push:
    branches:
      - main

jobs:
  build:
    name: INSTALL, BUILD & DEPLOY
    runs-on: ubuntu-latest
    
    steps:
      # ------------------------------------------------------------------------
      # Installs dependencies and generates static files inside the wwwroot folder
      - name: Generate static files in wwwroot
        uses: actions/setup-node@v3
        with:
          node-version: current
      - run: npm ci
      - run: npm run build

      # ------------------------------------------------------------------------
      - name: DEPLOY
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.CHEATSHEET_HOST }}
          username: ${{ secrets.CHEATSHEET_USERNAME }}
          password: ${{ secrets.CHEATSHEET_PASSWORD }}
          port: ${{ secrets.CHEATSHEET_PORT }}
          rm: true
          source: "_site/*"
          target: "/home/dh_swaz4r/tech.libresinn.com/1loc"
