# Category navigation example
# 
# - I haven't decided if the path will be required but it makes sense
#   to me to compare the paths to the categories. If that is the case
#   then I won't need to nest these which I think will be beneficial
# 
# - I hope to use the directories as the `Category` metadata instead of
#   having to set it in category property in the frontmatter
---
category-tree:
- name: Javascript
  desc: Language Specific things
  path: javascript

- name: Bash
  desc: Language Specific things
  path: bash

- name: Dotfiles
  desc: Language Specific things
  path: bash/dotfiles

- name: Commands
  desc: Useful & oft used `bash` commands
  path: bash/commands

- name: Libraries & Tools
  desc: Jest snippets

- name: Jest
  desc: Jest snippets

